version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8081:5000
    volumes:
      - .:/app
    networks:
      - network
    depends_on:
      - postgres
    links:
      - postgres:postgres
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    networks:
      - network
    depends_on:
      - postgres
    links:
      - postgres:postgres

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .db-data:/var/lib/postgresql/data
    networks:
      - network
    ports:
      - 5433:5432

networks:
  network:
    name: docker_network
    driver: bridge
    


  
