"""empty message

Revision ID: 21f2fd0379b2
Revises: fec6e7371df2
Create Date: 2021-03-19 21:55:47.995802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f2fd0379b2'
down_revision = 'fec6e7371df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product_user', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_user', type_='unique')
    # ### end Alembic commands ###
