version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - network
    depends_on:
      - db
    links:
      - db:db
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    networks:
      - network
    depends_on:
      - db
    links:
      - db:db
  
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - .db-data:/var/lib/postgresql/data
    networks:
      - network
    ports:
      - 5434:5432

networks:
  network:
    name: docker_network
    driver: bridge
    